### ISSUE TITLE
EventCalendar and Datatables formats display date-type query data incorrectly

### ISSUE THREAD

**Issue by RomStrom** [SemanticMediaWiki/SemanticResultFormats#210] opened 2017-05-01 18:36 UTC
### Setup

- MW version: 1.27.2 (1c409c5)
- DB (MySQL etc.): 5.5.52-MariaDB
- PHP version: 5.6.30 (apache2handler)
- SMW version: 2.5.1
- SRF version: 	2.4.2
- Browsers and versions (if applicable): Chrome 58.0.3029.81

### Issue

When querying date-type data for a Semantic Results Eventcalendar or Datatables format, such as;

```
{{#ask: [[Category:Meetings]]
|?Meeting type = Type
|?Meeting date = Date
|?Meeting start time = Time
|format=datatables
|limit=500
|link=all
|headers=show
|mainlabel = Meeting
}}
```

And assuming the value `Meeting date` is a property of type 'Date' set to `2017/02/13`, which would constitute the date February 13th, 2017, the table instead outputs `13 March 2016 `. In other words, the year is subtracted by one and the month is added by one.

Testing various months, these are the results;
i.e. Input Month --> Displayed Month
January --> January
February --> March
March --> March
April --> May
May --> May
June --> July
July --> July
August --> August
Sept. --> Oct.
Oct. --> Oct.
Nov. --> Nov.
Dec. --> Dec.

In every case, the year was subtracted by one.

A good example of this error can be seen with [this Eventcalendar example on the SMW website](https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Event_schedule). The example has SMWCon Fall 2012 displaying in Fall of 2011, even though the event dates are set in October of 2012.

I could only resolve this issue by switching `Meeting date` to a property of type 'Page', which resolved the issue for my Datatables as only a string would output. However, the tables as a result do not sort properly by date. And obviously, this work-around does not work for the eventcalendars.

**Comment by kghbln** [comment] 2017-05-01 19:21
> A good example of this error can be seen with this Eventcalendar example on the SMW website. The example has SMWCon Fall 2012 displaying in Fall of 2011, even though the event dates are set in October of 2012.

The year issue is a new variant which I do not observe for the example given. It is correctly showing the talks for 2012 in 2012.
![bildschirmfoto vom 2017-05-01 21-17-25](https://cloud.githubusercontent.com/assets/1104078/25591234/0922a95a-2eb4-11e7-8246-7db6d107171f.png)

When it comes to the date we are talking about a dupe to https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/205 here if I am not mistaken. As a workaround I set not just a date but also a time which is off changes caused by daylight savings. I know that this is painful.

**Comment by RomStrom** [comment] 2017-05-01 20:18
This is very strange... For me, the issue is replicated on my computer, two of my colleagues' computers, and my phone as well. I tried this both on Chrome and MS Internet Explorer browsers and in both cases, the events dont show in the correct dates.

**Eventcalendar At October 12-27th, 2012**
![capture2](https://cloud.githubusercontent.com/assets/27974094/25593106/e3f97c36-2e80-11e7-8df4-c6efbf53a2f4.PNG)

**Eventcalendar, same week in 2011**
![capture3](https://cloud.githubusercontent.com/assets/27974094/25593123/f70064c0-2e80-11e7-9ba1-be4bf8321c6a.PNG)

**Mobile Device, Same Issue Remains**
![screenshot_20170501-150148](https://cloud.githubusercontent.com/assets/27974094/25593150/0e3b0e1a-2e81-11e7-9070-5b5c8b10e07d.png)


And I dont think the date issue is the same as #205 , I am experiences differences in months and not just days, so I dont think this is the same issue.

**Comment by kghbln** [comment] 2017-05-01 20:28
An awkward situation. Whatever I do I get the correct results on Chrome and Firefox, logged in, not logged in. There is something in the water but I do not know what it is. Anyways thank you for reporting.

**Comment by RomStrom** [comment] 2017-05-01 20:32
Indeed. I'll notify if anything changes, thank you for the quick response.

**Comment by kghbln** [comment] 2017-05-03 14:59
I am still really puzzled how something like this can happen. Adding @mwjames as the author of the result format into the discussion.

**Comment by mwjames** [comment] 2017-05-03 15:21
Hi,

> I am still really puzzled how something like this can happen. Adding
> @mwjames as the author of the result format into the discussion.

The format hasn't changed for sometime and it worked then and now, so
unless there are replicable examples that can indicate the cause of an
issue, I'm unable to provide further assistance or input to this
discussion.

PS: Maybe this relates to some browser or server settings but this is
just a conjecture.

Cheers

**Comment by kghbln** [comment] 2017-05-03 15:24
> Maybe this relates to some browser or server settings but this is just a conjecture.

I had the server in mind but since this happed from several clients across the work place. Perhaps it is the server routing out the requests to the internet which is off by a year. Dunno. Perhaps @RomStrom could try from a different location not connected to the work place.

**Comment by mwjames** [comment] 2017-05-03 15:31
Hi,

You can have a look at the source page and see the actual data used.
Those data are encoded in the head with
"mw.config.set({"smw-...":"{\"query\":{\"result\ ..." including
references to dates like
"{\"timestamp\":\"1351184400\",\"raw\":\"1/2012/10/25/17/0/0/0\"}".

Cheers

**Comment by RomStrom** [comment] 2017-05-03 17:39
> Perhaps @RomStrom could try from a different location not connected to the work place.
When I viewed the page from my mobile phone, I was using the GSM network which I think would rule out the influence my work place server may have. Maybe its a regional thing? I'm based in Houston, TX.

@mwjames I was able to find this in the head of the html, and it seems like the correct 2012 dates are being referenced.
`(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"smw-590744c08fd2d":"{\"query\":{\"result\":{\"printrequests\":[{\"label\":\"\",\"key\":\"\",\"redi\":\"\",\"typeid\":\"_wpg\",\"mode\":2,\"format\":false},{\"label\":\"title\",\"key\":\"Has_title\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"},{\"label\":\"Has planned start\",\"key\":\"Has_planned_start\",\"redi\":\"\",\"typeid\":\"_dat\",\"mode\":1,\"format\":\"\"},{\"label\":\"Has planned finish\",\"key\":\"Has_planned_finish\",\"redi\":\"\",\"typeid\":\"_dat\",\"mode\":1,\"format\":\"\"},{\"label\":\"color\",\"key\":\"Has_event_color\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"},{\"label\":\"Description\",\"key\":\"Has_description\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"},{\"label\":\"Duration\",\"key\":\"Has_duration\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"},{\"label\":\"color\",\"key\":\"Has_event_color\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"},{\"label\":\"Has talk type\",\"key\":\"Has_talk_type\",\"redi\":\"\",\"typeid\":\"_txt\",\"mode\":1,\"format\":\"\"}],\"results\":{\"SMWCon Fall 2012/Architectural knowledge management with SMW\":{\"printouts\":{\"title\":[\"Architectural knowledge management with SMW\"],\"Has planned start\":[{\"timestamp\":\"1351184400\",\"raw\":\"1/2012/10/25/17/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351185600\",\"raw\":\"1/2012/10/25/17/20/0/0\"}],\"color\":[\"#E07628\"],\"Description\":[\"Here we want to describe some of our work on architectural knowledge management with SMW for the Dutch e-government, especially our recent work on an interconnected system of semantic wiki's.\"],\"Duration\":[\"20 minutes\"],\"Has talk type\":[\"Talk\"]},\"fulltext\":\"SMWCon Fall 2012/Architectural knowledge management with SMW\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Architectural_knowledge_management_with_SMW\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Architectural knowledge management with SMW\"},\"SMWCon Fall 2012/BlueSpice\":{\"printouts\":{\"title\":[\"BlueSpice\"],\"Has planned start\":[{\"timestamp\":\"1351175400\",\"raw\":\"1/2012/10/25/14/30/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351177200\",\"raw\":\"1/2012/10/25/15/0/0/0\"}],\"color\":[],\"Description\":[\"The description of BlueSpice - an easy-to-use enterprise MediaWiki bundle. What are the common obstacles the developers of the BlueSpice and SMW now have? Can BlueSpice take advantage of including SMW into the bundle?\"],\"Duration\":[\"30 minutes\"],\"Has talk type\":[\"Presentation\"]},\"fulltext\":\"SMWCon Fall 2012/BlueSpice\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/BlueSpice\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"BlueSpice\"},\"SMWCon Fall 2012/Brain-Inspired Expertise Management\":{\"printouts\":{\"title\":[\"Brain-Inspired Expertise Management\"],\"Has planned start\":[{\"timestamp\":\"1351263000\",\"raw\":\"1/2012/10/26/14/50/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351264500\",\"raw\":\"1/2012/10/26/15/15/0/0\"}],\"color\":[],\"Description\":[\"Using SMW and brain-inspired expertise management ontology for expertise management\"],\"Duration\":[\"25 minutes\"],\"Has talk type\":[\"Presentation\"]},\"fulltext\":\"SMWCon Fall 2012/Brain-Inspired Expertise Management\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Brain-Inspired_Expertise_Management\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Brain-Inspired Expertise Management\"},\"SMWCon Fall 2012/Cicero, supporting collaborative decision and design processes\":{\"printouts\":{\"title\":[\"Cicero: Supporting collaborative decision and design processes\"],\"Has planned start\":[{\"timestamp\":\"1351180800\",\"raw\":\"1/2012/10/25/16/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351182000\",\"raw\":\"1/2012/10/25/16/20/0/0\"}],\"color\":[],\"Description\":[\"Cicero is an SMW-based extension to support structured discussions\"],\"Duration\":[\"20-30 minutes\"],\"Has talk type\":[]},\"fulltext\":\"SMWCon Fall 2012/Cicero, supporting collaborative decision and design processes\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Cicero,_supporting_collaborative_decision_and_design_processes\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Cicero, supporting collaborative decision and design processes\"},\"SMWCon Fall 2012/Collaborative Financial Analysis using Semantic MediaWiki\":{\"printouts\":{\"title\":[\"Collaborative Financial Analysis using Semantic MediaWiki\"],\"Has planned start\":[{\"timestamp\":\"1351183200\",\"raw\":\"1/2012/10/25/16/40/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351184400\",\"raw\":\"1/2012/10/25/17/0/0/0\"}],\"color\":[\"#E07628\"],\"Description\":[\"Using Semantic MediaWiki for a more agile approach of collaborative budgeting, expense planning, and analysis in a use case of finance management within a research group.\"],\"Duration\":[\"20 minutes\"],\"Has talk type\":[\"Talk\"]},\"fulltext\":\"SMWCon Fall 2012/Collaborative Financial Analysis using Semantic MediaWiki\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Collaborative_Financial_Analysis_using_Semantic_MediaWiki\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Collaborative Financial Analysis using Semantic MediaWiki\"},\"SMWCon Fall 2012/Crowdsourcing KA\":{\"printouts\":{\"title\":[\"Crowdsourcing knowledge acquisition via SMW+\"],\"Has planned start\":[{\"timestamp\":\"1351260000\",\"raw\":\"1/2012/10/26/14/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351261500\",\"raw\":\"1/2012/10/26/14/25/0/0\"}],\"color\":[],\"Description\":[],\"Duration\":[\"25 minutes\"],\"Has talk type\":[\"Presentation\"]},\"fulltext\":\"SMWCon Fall 2012/Crowdsourcing KA\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Crowdsourcing_KA\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Crowdsourcing KA\"},\"SMWCon Fall 2012/Current status and next steps for SMW\":{\"printouts\":{\"title\":[\"Current status and next steps for SMW\"],\"Has planned start\":[{\"timestamp\":\"1351162800\",\"raw\":\"1/2012/10/25/11/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351164600\",\"raw\":\"1/2012/10/25/11/30/0/0\"}],\"color\":[],\"Description\":[\"The yearly \\\"what happened and what are we working on now\\\" talk\"],\"Duration\":[\"30 minutes\"],\"Has talk type\":[\"Presentation\"]},\"fulltext\":\"SMWCon Fall 2012/Current status and next steps for SMW\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Current_status_and_next_steps_for_SMW\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Current status and next steps for SMW\"},\"SMWCon Fall 2012/Customizing MediaWiki skin actions with SMW\":{\"printouts\":{\"title\":[\"Customizing MediaWiki skin actions with SMW\"],\"Has planned start\":[{\"timestamp\":\"1351080000\",\"raw\":\"1/2012/10/24/12/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351080300\",\"raw\":\"1/2012/10/24/12/5/0/0\"}],\"color\":[],\"Description\":[\"Micro-tutorial on improving the wiki UI using SMW data\"],\"Duration\":[\"5 minutes\"],\"Has talk type\":[\"Lightning talk\"]},\"fulltext\":\"SMWCon Fall 2012/Customizing MediaWiki skin actions with SMW\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Customizing_MediaWiki_skin_actions_with_SMW\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Customizing MediaWiki skin actions with SMW\"},\"SMWCon Fall 2012/Developing SMW (extensions)\":{\"printouts\":{\"title\":[\"Developing SMW (extensions)\"],\"Has planned start\":[{\"timestamp\":\"1351089000\",\"raw\":\"1/2012/10/24/14/30/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351090800\",\"raw\":\"1/2012/10/24/15/0/0/0\"}],\"color\":[\"#BF381A\"],\"Description\":[\"An introduction to how to develop Semantic MediaWiki and extensions\"],\"Duration\":[\"30 minutes\"],\"Has talk type\":[\"Technical talk\"]},\"fulltext\":\"SMWCon Fall 2012/Developing SMW (extensions)\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Developing_SMW_(extensions)\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Developing SMW (extensions)\"},\"SMWCon Fall 2012/Fighting Spam in MediaWiki\":{\"printouts\":{\"title\":[\"Fighting Spam in MediaWiki\"],\"Has planned start\":[{\"timestamp\":\"1351087200\",\"raw\":\"1/2012/10/24/14/0/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351089000\",\"raw\":\"1/2012/10/24/14/30/0/0\"}],\"color\":[\"#BF381A\"],\"Description\":[\"All about spam and how to prevent it\"],\"Duration\":[\"30 minutes\"],\"Has talk type\":[\"Technical talk\"]},\"fulltext\":\"SMWCon Fall 2012/Fighting Spam in MediaWiki\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Fighting_Spam_in_MediaWiki\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Fighting Spam in MediaWiki\"},\"SMWCon Fall 2012/Filtered result format\":{\"printouts\":{\"title\":[\"Filtered result format\"],\"Has planned start\":[{\"timestamp\":\"1351261800\",\"raw\":\"1/2012/10/26/14/30/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351263000\",\"raw\":\"1/2012/10/26/14/50/0/0\"}],\"color\":[\"#E07628\"],\"Description\":[\"A talk about the new Filtered result format\"],\"Duration\":[\"20 minutes\"],\"Has talk type\":[\"Talk\"]},\"fulltext\":\"SMWCon Fall 2012/Filtered result format\",\"fullurl\":\"https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2012/Filtered_result_format\",\"namespace\":0,\"exists\":\"1\",\"displaytitle\":\"Filtered result format\"},\"SMWCon Fall 2012/Improvements in SQLStore3\":{\"printouts\":{\"title\":[\"Improvements in SQLStore3\"],\"Has planned start\":[{\"timestamp\":\"1351164900\",\"raw\":\"1/2012/10/25/11/35/0/0\"}],\"Has planned finish\":[{\"timestamp\":\"1351166100\",\"raw\":\"1/2012/10/25/11/55/0/0\"}],\"color\":[],\"Description\":[\"Things done to make your wiki faster\"],\"Duration\":[\"2…`

**Comment by mwjames** [comment] 2017-05-06 08:27
Closing this in reference to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2440 which contains the analysis of the root cause.

**Closed by mwjames** 2017-05-06 08:27 UTC
Labels: bug
