### ISSUE TITLE
Process: Broken with GraphViz 1.3.1

### ISSUE THREAD

**Issue by formwandler** [SemanticMediaWiki/SemanticResultFormats#66] opened 2014-08-24 08:36 UTC
The process format does not work at all using MW 1.23.2 with extensions SMW 2.0, SRF 2.0 and GraphViz 1.3.1.

1) Using the Process format results in debug message 'The SRF Graph printer needs the GraphViz extension to be installed.' This is due the "renderGraphviz" method does not work (any more) - line 204:

`if ( !is_callable( 'renderGraphviz' ) )`

2) I changed the method call from `renderGraphviz` to `GraphViz::graphvizParserHook`, that is used within the graph format. Well, at least an image with the process diagram is created now. But it isn't displayed on the page, it's just created in the wiki image namespace. And, even worse: Each time the page with the embedded ask query is accessed, a new image is created.

So, it seems that this process format is outdated and does not work with the recent GraphViz extension. Would be great to fix this and maybe also to improve the documentation about this format.

See my example: https://www.kruedewagen.de/wiki/Process1

**Comment by s7eph4n** [comment] 2017-06-10 02:48
Probably duplicate of #49

**Comment by kghbln** [comment] 2017-06-10 15:40
> Probably duplicate of #49

Moreover GraphViz has undergone a major overhaul and is now at v2+. As the [example shows](https://sandbox.semantic-mediawiki.org/wiki/Mise_en_place_d%27un_wiki) the process format is working now.

**Closed by kghbln** 2017-06-10 15:40 UTC
Labels: bug, duplicate
