### ISSUE TITLE
Filtered format breaks with properties of type:page

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#568] opened 2020-02-24 11:24 UTC
### Setup

- MW version: 1.31.6
- DB (MySQL etc.): 10.3.22-MariaDB
- PHP version: 7.2.14 (fpm-fcgi)
- SMW version: 3.1.4
- SRF version: 3.1.0
- Browsers and versions (if applicable): FF and Chrome, latest versions

### Issue
Filtered format show the blue "loading" icon and never finishes if a property of type page is in the query. 

### Reproducing
1. Create a simple ask query for properties NOT of type page.
2. format filtered works
3. change property type of one of the selected properties in the printout to type page
4. result: filtered format breaks
5. now change format=filtered to something else, e. g. fomat=table and you will see the query results with no problems.

### Errors
Console shows:
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at ../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure script ..Vendor/onoi/shared-resources/res/localForage/localforage.min.js'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure script '../Vendor/onoi/shared-resources/res/md5/jquery.md5.js'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure script '../Vendor/onoi/shared-resources/res/jquery.qtip/extended/jquery.qtip.js'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure script '../Vendor/onoi/shared-resources/res/onoi.blobstore.js'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure script '../Vendor/onoi/shared-resources/res/onoi.util.js'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure stylesheet '../Vendor/onoi/shared-resources/res/onoi.util.css'. This request has been blocked; the content must be served over HTTPS.
ext.summaryCards.js?99f7e:456 Uncaught ReferenceError: onoi is not defined
    at ext.summaryCards.js?99f7e:456
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure stylesheet '../Vendor/onoi/shared-resources/res/jquery.qtip/extended/jquery.qtip.css'. This request has been blocked; the content must be served over HTTPS.
Filtered-Test?debug=true:1 Mixed Content: The page at '../Filtered-Test?debug=true' was loaded over HTTPS, but requested an insecure stylesheet '../Vendor/onoi/shared-resources/res/onoi.util.css'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by krabina** [comment] 2020-02-24 11:55
When trying to reproduce it in sandbox, first both did not work at all
* https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/568
* https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/246

Then I figured that if you hit ctrl+F5 (clearing cache in FF) resolves the problem. However, after saving the page it was there again and you have to clear the cache every time.

Now both 568 and 246 seem to work, but older veresions of 568 still don't:
https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/568&oldid=46347

**Comment by kghbln** [comment] 2020-02-24 16:27
> Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.

I wonder why we are getting mixed content warnings here.

**Comment by krabina** [comment] 2020-02-24 22:03
Please forget my stacktrace. I have the feeling it has more to do with Summary Cards extension. I de-installed this one.

Currently, when I use format=table or format=filtered on a test page and add &debug=true, both output the same three warnings and no errors:

```
DevTools failed to parse SourceMap: ../extensions/Bootstrap/resources/bootstrap/js/popper.js.map
DevTools failed to parse SourceMap: ../extensions/SemanticMediaWiki/res/libs/tippy/popper.min.js.map
DevTools failed to parse SourceMap: ../extensions/SemanticMediaWiki/res/libs/tippy/index.js.map
```

I also tried to rebuild all data in SMW with no effect.

**Comment by kghbln** [comment] 2020-02-25 08:26
> Please forget my stacktrace. I have the feeling it has more to do with Summary Cards extension. I de-installed this one.

Just to make sure. This was not a stack trace from sandbox. If it was we need to create an issue with Summary Cards.

**Comment by krabina** [comment] 2020-02-25 12:10
no, it was from my testwiki.
I will try to see if re-installing SummaryCards will show up these problems and then will file a bug report there.

More important for me at the moment is this issue....

**Comment by kghbln** [comment] 2020-02-25 14:22
> no, it was from my testwiki.

Thanks for confirming.

>  I will try to see if re-installing SummaryCards will show up these problems and then will file a bug report there.

Cool. Make sure to make the website HTTPS only for best test results.

> More important for me at the moment is this issue....

No objection at all. :)

**Comment by krabina** [comment] 2020-03-05 11:31
short update: I did everything described here: https://www.semantic-mediawiki.org/wiki/Help:Repairing_SMW%27s_data#Rebuilding_everything

and deactivated every extension except SMW and SRF.

Still no luck...

**Comment by krabina** [comment] 2020-03-05 11:33
A working filtered list shows this in the sourcode with ?debug=true

 "srfFilteredConfig": {
        "gcja438f1c": {
            "query": "[[Kategorie:Expertinnen und Experten]]",
            "printrequests": {
                "dhyp4unk2a880k4w8gc04c0co": {
                    "mode": 2,
                    "label": "",
                    "outputformat": false,
                    "type": "_wpg"
                },
                "72mo4x0s0ps0owo4gcgo8go80": {
                    "mode": 1,
                    "label": "Geschlecht",
                    "outputformat": "-",
                    "type": "_txt",
                    "property": "Geschlecht"
                },
                "d0vm12nhw7scs4sogks48gsw": {
                    "mode": 1,
                    "label": "Wirkungsraum",
                    "outputformat": "-",
                    "type": "_txt",
                    "property": "Wirkungsraum"
                },
                "ajfcz5wlgxs08gg4okc8go8ok": {
                    "mode": 1,
                    "label": "Position",
                    "outputformat": "-",
                    "type": "_txt",
                    "property": "Position"
                }
            },
            "views": {
                "gcja438aks": {
                    "type": "table"
                }
            },

As soon as I add one printout of a property of type Page, this is missing in the source code and that's why the blue icon does not stop and no results are displayed.

**Comment by gesinn-it** [comment] 2020-03-18 16:52
Any JS errors?

**Comment by krabina** [comment] 2020-03-18 18:07
no.

**Comment by krabina** [comment] 2020-03-19 09:30
Here are some warning messages that appear:

```
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: ../extensions/SemanticMediaWiki/res/libs/tippy/popper.min.js?74d0b Source-Map-Adresse: popper.min.js.map
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: ../extensions/SemanticMediaWiki/res/libs/tippy/tippy.js?e5280
Source-Map-Adresse: index.js.map
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.wikiPage.js?5bdf7". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.uri.js?944c2". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.time.js?ea817". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.property.js?eaf65". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.unknown.js?36eef". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.number.js?a7ed6". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.text.js?951c9". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataItem.geo.js?920cc". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "../extensions/SemanticMediaWiki/res/smw/data/ext.smw.dataValue.quantity.js?98b3c". index.php:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "./extensions/SemanticMediaWiki/res/smw/data/ext.smw.data.js?51da0".
```
"Laden fehlgeschlagen.." = "Loading failed for the script..."

**Comment by krabina** [comment] 2020-03-29 09:10
another hint in yet another installation (bitami mediawiki in AWS):

SyntaxError: expected expression, got ';'Projects:6:54

row 6 is
`<script>document.documentElement.className="client-js";RLCONF=;RLSTATE={"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.legacy.commonPrint":"ready","jquery.tablesorter.styles":"ready","mediawiki.skinning.content":"ready","zzz.ext.bootstrap.styles":"ready","ext.srf.styles":"ready","ext.smw.style":"ready","ext.smw.tooltip.styles":"ready"};RLPAGEMODULES=["ext.smw.style","ext.smw.tooltips","ext.srf.filtered.value-filter","ext.srf.filtered.number-filter","ext.srf.filtered.map-view","ext.srf.filtered","site","mediawiki.page.startup","mediawiki.page.ready","jquery.tablesorter","mediawiki.searchSuggest","mediawiki.page.watch.ajax","ext.bootstrap.scripts","ext.smw.purge"];</script>
`
If I remove the only property "Organizer" of the query that is of type page, it works and this error does not show up.

MediaWiki | 1.34.1
-- | --
PHP | 7.3.16 (fpm-fcgi)
MySQL | 8.0.18
ICU | 66.1

**Comment by JeroenDeDauw** [comment] 2020-04-07 19:18
I looked into this a bit and while I did not find the root cause or fix yet, here are some findings already.

The bug

* only happens when values of type page are present
* does not happen when none of the pages have a value for the property of type page
* happens when there is a single value of type page and when all result rows have one
* happens both for values pointing to existing pages and for redlinks

The non-working pages [missing `srfFilteredConfig` in the page output](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/568#issuecomment-595183766) is very likely what is causing the loading to fail. Unfortunately I cannot reproduce this on my wiki, which makes it very hard to track down further.

![image](https://user-images.githubusercontent.com/146040/78709630-414b9280-7914-11ea-8b4f-8da7d5a25e7f.png)

My guess is that something is going wrong with the `$config` variable before it gets to this point: https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/3.1.0/formats/filtered/src/Filtered.php#L209 It's surprising there is no error though. It'd be good to inspect and see what value `$config` has on the broken pages.

**Comment by JeroenDeDauw** [comment] 2020-04-07 19:54
@krabina I don't know what debug config you have in your LocalSettings.php file. Perhaps no error is shown because it is being hidden by MW. You could try adding the following:

```php
error_reporting( -1 );
ini_set( 'display_errors', '1' );

$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgShowDBErrorBacktrace = true;
$wgDebugToolbar = true;
$wgShowDebug = true;
$wgShowExceptionDetails = true;
```

Don't do that on a production wiki though, especially not for a longer period, as this is bad for security.

**Comment by JeroenDeDauw** [comment] 2020-04-09 18:08
I narrowed down the problem. It is coming from SMWs `getSortKey` method on `DataItem` and can be avoided with this change https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/d061308b5d2c80cd8ac863435b25772da54d028b

This method, for whatever reason, is returning text with messed up enconding. Which then causes the whole `$config` array to not be output to the page. Example:

![image](https://user-images.githubusercontent.com/146040/78926616-ab437380-7a9d-11ea-8409-b59d7a09d058.png)

Good chance that this is a server specific issue, with the root cause being some config or database issue. Bit weird the messed up encoding is just showing up here though.

**Comment by mwjames** [comment] 2020-04-09 18:34
> I narrowed down the problem. It is coming from SMWs `getSortKey` method on
> `DataItem` and can be avoided with this change

There is nothing wrong with the DB or the DataItem because if the
users decides to generated sortkeyes for entities with an uca
collation [0] (see `$smwgEntityCollation` [1]) then entities will
honor that setting by transferring the key that has been generated via
the collator instance for this representation.

[0] https://en.wikipedia.org/wiki/Unicode_collation_algorithm
[1] https://www.semantic-mediawiki.org/wiki/Help:$smwgEntityCollation

**Comment by krabina** [comment] 2020-04-09 21:35
hmm. Indeed my settings are
```
$wgCategoryCollation = "uca-de-u-kn";
$smwgEntityCollation = "uca-de-u-kn";
```
as I thought they should be in a German language installation. 

And indeed, in a wiki where the problem did not show, I did not have these set. After setting them and performing 
`updateEntityCollation.php
`
the problem now is showing up. 

The reverse is also true: if I remove those settings and do a
`updateEntityCollation.php
`
then the problem goes away.

So now the question remains, how to set it up correctly for a German (or other) language installation. I'd like the list of pages get sorted correctly...

**Comment by kghbln** [comment] 2020-04-09 21:41
MediaWiki sets: [`$wgCategoryCollation = 'uppercase';`](https://noc.wikimedia.org/conf/highlight.php?file=InitialiseSettings.php) and so does German Wikipedia. On a German language instance I'd stick to what Wikipedia does for de.

**Comment by krabina** [comment] 2020-04-09 22:06
I disagree. I couldn't care less what the German Wikipedia does. In an enterprise Wiki, I need the sorting to be as user-friendly as it can get and since this great option is there, I see it as a great opportunity to have correct sorting in any language. 

You do realize, that I as Austrian did not set de-AT@collation=phonebook  ;-)
(Which is even more preferrable. I think I tried it out at some point but it did not work.)

**Comment by krabina** [comment] 2020-04-09 22:26
btw. at least `numeric `as setting works also, but as soon as you use a uca collation, it fails.

**Comment by mwjames** [comment] 2020-04-11 10:29
> btw. at least numeric as setting works also, but as soon as you use a uca collation, it fails.

Of course, because `numeric` has nothing to do with the UCA.

UCA (Unicode collation algorithm) represents a sorting string of calculated codepoints that may contain "invalid" characters [0] due to UCA using a larger UTF (most common UTF-8, UTF-16, UTF-32 [1]) encoding set to build a sort string (see the provided link for more information about UCA). In case the JS cannot deal with those character representations, you need to transform the sort string into something that is UTF-8 safe which can be done in PHP via `$sort = json_encode( $sort, JSON_INVALID_UTF8_SUBSTITUTE )` (only PHP 7.2+) or `$sort = mb_convert_encoding( $sort, 'UTF-8', 'UTF-8' );` it goes without saying that you are loosing some information about the sorting string but it is surely better than to assume a non UCA sort specially for those items where lexicographic sorting is bound to language dependent rule sets.

[0] https://stackoverflow.com/questions/1301402/example-invalid-utf8-string
[1] https://en.wikipedia.org/wiki/Comparison_of_Unicode_encodings

**Comment by krabina** [comment] 2020-04-21 10:51
Why is this closed? I interpret the comment of @mwjames that some transformaton needs to be done in JavaScript. Adding smwgEntityCollation to the upgrade key matrix is nice, but does not help, since my settings were not incorrect and I did run both update-scripts after changing the collation.

IMO it is still a bug that if you set the collation to UCA (a documented feature) the filtered format cannot handle it correctly.

**Comment by JeroenDeDauw** [comment] 2020-04-21 10:58
My bad. I did not realize further discussion had happened and was under the impression the root cause was unsupported config.

**Comment by D-Groenewegen** [comment] 2020-08-28 14:43
SMW 3.1.6 + SRF 3.1.0

Thanks @krabina. I may have the same 'spinning wheel in perpetual motion' problem, although removing properties of type page does not help here. Nothing to see in the console or error reporting messages.

**Comment by krabina** [comment] 2020-08-28 15:31
did you check your collation settings. the bug goes away if you don't use UCA collation...

**Comment by D-Groenewegen** [comment] 2020-08-29 20:20
Atm, I can't test this I'm afraid. Uca collation is essential to the website and in the absence of a staging environment, I don't have the luxury position where I can simply switch it on and off. It's not a trivial thing either.

**Comment by gesinn-it** [comment] 2021-11-09 14:04
we need to make sure to get this covered by tests

**Closed** 2021-11-23 10:22 UTC
Labels: bug

**Comment by krabina** [comment] 2021-11-23 11:01
Currently I am not able to reproduce this bug on MW 1.35, so I cannot confirm that #686 fixes it.
@D-Groenewegen  - can you look into this?

**Comment by krabina** [comment] 2021-11-23 11:07
I look into this and was able to reproduce the bug in MW 1.35. Upgrading to the latest dev-master of SRF fixes the issue!
Thank you @gesinn-it-gea!!
