### ISSUE TITLE
Unknown module: onoi.dataTables after MW upgrade 1.35.8 -> 1.39.1

### ISSUE THREAD

**Issue by lyrixn** [SemanticMediaWiki/SemanticResultFormats#766] opened 2023-02-20 11:13 UTC
### Setup

- MW version: 1.39.1
- DB (MySQL etc.): MySQL 8.0.32
- PHP version: 7.4.33
- SMW version: 4.1.0
- SRF version: 4.0.1
- Browsers and versions (if applicable): Chrome/Edge latest

### Issue

After upgrading our wiki from 1.35.8 to 1.39.1 we have a never ending loading screen on all of our data tables with the following console warnings:
Skipped unavailable module smw.tableprinter.datatable
Error: Unknown module: onoi.dataTables
![fiPnQwJ](https://user-images.githubusercontent.com/20580599/220089904-b8be3c0b-6f43-4e6b-8b4b-b0f3045de7cc.png)

**Comment by JeroenDeDauw** [comment] 2023-02-20 20:16
Did you run `composer update` or similar? That issue makes me think you somehow got rid of some required packages.

**Comment by lyrixn** [comment] 2023-02-21 03:51
I ran _composer update --no-dev_ to be precise. Weirdly enough "onoi" is still under /vendor, along with datatables if that's at all relevant.
```
/var/www/wiki/w/vendor/onoi/shared-resources/res$ ls -la
total 72
drwxr-xr-x 13 ubuntu ubuntu 4096 Feb 20 10:05 .
drwxr-xr-x  3 ubuntu ubuntu 4096 Feb 20 10:05 ..
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 bootstrap
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 clipboard
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jStorage
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jquery.async
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jquery.blockUI
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jquery.dataTables
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jquery.highlight
drwxr-xr-x  4 ubuntu ubuntu 4096 Feb 20 10:05 jquery.qtip
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 jquery.rangeSlider
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 localForage
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 20 10:05 md5
-rw-r--r--  1 ubuntu ubuntu 3234 Feb 20 10:05 onoi.blobstore.js
-rw-r--r--  1 ubuntu ubuntu  486 Feb 20 10:05 onoi.clipboard.js
-rw-r--r--  1 ubuntu ubuntu 4929 Feb 20 10:05 onoi.util.css
-rw-r--r--  1 ubuntu ubuntu 1840 Feb 20 10:05 onoi.util.js
```

**Comment by lyrixn** [comment] 2023-02-25 09:39
Just an update, that I never figured out what the problem was and reverted back to MW 1.35, where it works perfectly.

**Comment by JeroenDeDauw** [comment] 2023-03-08 20:41
Duplicate of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5331

**Comment by JeroenDeDauw** [comment] 2023-03-08 21:46
> @thomas-topway-it @krabina Might be related to your changes

It is not. I found the cause and made a fix: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5458

Having a closer look at those libraries and updating them with versions that are not 7 years old might be something of interest to you? :)

**Closed** 2023-03-08 22:32 UTC
Labels: bug
