### ISSUE TITLE
Datatables and EventCalendar Stuck with Loading Dots

### ISSUE THREAD

**Issue by acminor** [SemanticMediaWiki/SemanticResultFormats#648] opened 2021-03-25 23:12 UTC
### Setup

- MW version: 1.35.1
- DB (MySQL etc.): SQLite 3.27.2
- PHP version: 7.3.27 (apache2handler)
- SMW version: 3.2.2
- SRF version: 3.2.0
- Browsers and versions (if applicable): Tested with current Firefox 86.0.1 and Safari (iPad)

### Issue

I tried to use the eventcalendar format for displaying a calendar in my personal wiki. The loading-dots never disappeared. I have tried to diagnose the issue; however, I have not been able to determine why the loading-dots never disappear. It appears that maybe the javascript for the eventcalendar is never loaded.

The same issue persists for datatables format as well.

**Steps to reproduce**

I cannot read French so using the sandbox is a little difficult.
Below are the steps.

1. Create a test event on page `Test calendar event`
```
[[Has event::Test Event]]
[[Has event start::2021-03-25]]

[[Category:Calendar test]]
```
2. Create empty `Category:Calendar test`
3. Create a calendar wiki page `Calendar test`
```
{{#ask:
 [[Category:Calendar test]]
 |?Has event=title
 |?Has event start
 |?Has event end
 |?Has event description=description
 |?Has event icon=icon
 |?Has event color=color
 |?Has event location=location
 |legend=top
 |format=eventcalendar
 |defaultview=month
}}
```

**Expected result:**

Calendar will pull up.

**Observed result:**

Stuck with the loading "..." GIF.

**Stacktrace** 

No stack trace.

**Comment by kghbln** [comment] 2021-03-26 07:37
Thanks for reporting. This can also be observed on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/648)-

Browser console gives this error:
```
Error: Unknown module: jquery.ui.core
    sortDependencies https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:8
    sortDependencies https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:8
    sortDependencies https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:8
    resolveStubbornly https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:9
    load https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:20
    <anonymous> https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:61
    <anonymous> https://sandbox.semantic-mediawiki.org/w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=medik:61
load.php:2:567
```

**Comment by gesinn-it** [comment] 2021-04-03 14:59
TODO: Verify, if https://phabricator.wikimedia.org/T219604 is related

**Comment by gesinn-it** [comment] 2021-04-03 15:04
See #621

**Comment by kghbln** [comment] 2021-04-06 06:39
> See #621

So we need to break compat with 1.31 or is there another way?

**Comment by gesinn-it** [comment] 2021-04-06 06:45
@kghbln I did not have time to look into it in detail if it could be fixed without breaking compat with 1.31. I think it is important to make JS testing a part of the CI workflow. A part of this journey is #652 .

**Comment by gesinn-it** [comment] 2021-04-06 06:51
@kghbln I would definitely not break compat with 1.31 until both, SMW and SRF are fully ready for MW 1.35. If technically required, we should branch 4.x.

**Comment by danielriedmueller** [comment] 2021-04-15 11:19
Hello! I have the same issue. Just wanted to ask if there is an solution already? Thank you!

**Comment by gesinn-it** [comment] 2021-04-15 11:22
@danielriedmueller you can try to patch your installation with fixes provided by #621 and share with us, if this worked for you.

**Comment by danielriedmueller** [comment] 2021-04-19 08:25
I replaced Resources.php with the the modified one from the patch, and it didnt work unfortunately. Same error.

**Comment by acminor** [comment] 2021-04-20 14:14
I can also confirm that I can get datatables loading with the corrected Resources.php.

**Comment by kghbln** [comment] 2021-05-05 19:49
In SimpleBatchUpload this code was added to help the cause: https://github.com/ProfessionalWiki/SimpleBatchUpload/blob/master/src/SimpleBatchUpload.php#L99

**Comment by Megajoul** [comment] 2021-11-11 10:20
Sorry but #653 is still not solved with #621

**Comment by gesinn-it** [comment] 2021-11-11 10:27
... we are at the moment fixing QUnit tests. there is definitley something in the water. Stay tuned.

**Comment by kghbln** [comment] 2022-02-10 21:01
I guess in the meantime it is pointless to try adding some shim to support both MW 1.31 an 1.35. On 1.31 you need to use SRF 3.2.x and on MW 1.35 SRF 4.0.x.

For SRF 4.0.x on MW 1.35.x the eventcalendar works gain. Thus closing.

**Closed by kghbln** 2022-02-10 21:01 UTC
Labels: bug
